Repository chingu-voyage4/Bears-Team-15, pull requests merged in 2018-02, with the labels that each got.

#3 docs: about project closes #1
  README.md
Labels: review

#5 docs: waffle badge
  README.md
Labels: review

#21 chore: add vue and express boilerplate
  .babelrc
  .editorconfig
  .gitignore
  .postcssrc.js
  build/build.js
  build/check-versions.js
  build/logo.png
  build/utils.js
  build/vue-loader.conf.js
  build/webpack.base.conf.js
  build/webpack.dev.conf.js
  build/webpack.prod.conf.js
  config/dev.env.js
  config/index.js
  config/prod.env.js
  index.html
  package-lock.json
  package.json
  server/app.js
  server/routes/index.js
  src/App.vue
  src/assets/logo.png
  src/components/HelloWorld.vue
  src/main.js
  src/router/index.js
  static/.gitkeep
Labels: review

#22 Documentation
  README.md
Labels: docs, review

#23 chore: make Homepage component and set as root
  index.html
  package-lock.json
  src/App.vue
  src/components/HelloWorld.vue
  src/components/Homepage.vue
  src/router/index.js
Labels: review

#25 update dev from master
  README.md
Labels: review

#32 feat: Create basic Homepage
  src/App.vue
  src/assets/logo-placeholder.png
  src/components/Dashboard.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/Homepage.vue
  src/components/Lesson.vue
  src/router/index.js
Labels: feature, homepage

#33 feat: lesson page
  src/components/Card.vue
  src/components/Lesson.vue
Labels: feature, lesson

#27 docs: Add contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: docs

#36 feat: adds vuex store and one new collection closes #14
  src/components/Lesson.vue
  src/main.js
  src/store/index.js
Labels: in progress

#41 version 0.2
  CONTRIBUTING.md
  README.md
  src/App.vue
  src/assets/logo-placeholder.png
  src/components/Card.vue
  src/components/Dashboard.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/Homepage.vue
  src/components/Lesson.vue
  src/main.js
  src/router/index.js
  src/store/index.js
Labels: review

#55 chore: Update server accordingly to master branch
  package.json
  server/app.js
  server/routes/index.js
Labels: review

#57 collection component uses vuex store
  src/components/Collection.vue
Labels: review
